---
npc_configurations:
- tag: "town_guard"
  text: "Don't make any trouble in the town."
  sprite: "guard"
- tag: "town_merchant"
  text: "Care to take a look at my wares?"
  sprite: "merchant"
  default_inventory:
    - "Apple"
    - "Apple"
    - "Apple"
    - "Apple"
    - "red-potion"
    - "red-potion"
    - "blue-potion"
  current_inventory:
    - "Apple"
    - "Apple"
    - "Apple"
    - "Apple"
    - "red-potion"
    - "red-potion"
    - "blue-potion"
- tag: "town_blacksmith"
  text: "I've got some pretty good pieces if you want to take a look."
  sprite: "blacksmith"
  default_inventory:
    - "iron_sword"
    - "iron_helmet"
  current_inventory:
    - "iron_sword"
    - "iron_helmet"
- tag: "town_villager"
  text: "yeah yeah yeah"
  sprite: "villager"
- tag: "pub_maid"
  text: "Welcome to the Twilight Pub"
  sprite: "maid"